### ISSUE TITLE
회원 서버 구현

### ISSUE THREAD

**Issue by 9JaHyun** [9JaHyun/auth-system#2]
# 회원 서버 구현
## TODO
- [x] 회원 도메인 엔티티 구현
- [x] DB Adapter 구현
  - [x] Persistence
  - [x] Redis
- [x] 회원 가입 API 구현
  - [x] Web Adapter 계층
    - [x] input validator 구현
  - [x] Port 계층
  - [ ] Service 계층 (Business logic)
    - [ ] 비밀번호 암호화
    - [x] 인증 코드 이메일 전송 및 redis 저장
    - [x] business validator 구현

### 회원 상태 관리
회원 상태 관리는 총 세가지로 나뉩니다.
* DEACTIVATED - 이메일 미인증 상태
* ACTIVATED - 이메일 인증 상태
* DELETED - 계정 삭제 상태 (바로 DB에서 지우지 않고 1년동안 저장 후 배치를 사용해 삭제)

### 인증 정책
인증 정책은 다음과 같습니다.
* 회원가입 시 미인증 상태. 추후 인증을 해야 함.
* 인증 URI 전송
  * queryParam으로 username, email, authcode가 들어가있음.
  * authcode는 UUID를 사용해 전송.
  * 세 개의 정보를 사용해 redis 저장.
  * 해당 링크 접속 시 인증 완료.

### Email 정책
* 회원가입 시 기본적으로 전송해주고 실패 가능성을 산정해 얼마든지 인증 이메일을 전송할 수 있도록 설정.
* 단, 악의적인 리소스 사용 방지를 위해 횟수 제한을 둘 예정. (하루 3회)
  * 간단하게 bucket 방식을 사용.
  * 단, 트래픽 자체를 제어하는 방식은 적용되지 않기 때문에 게이트웨이에 트래픽 제한 장치 배치를 고려하자.
